Rails.application.routes.draw do
  root                     'countries#home'
  get 'contact'         => 'countries#contact'
  get 'south_korea'     => 'countries#south_korea'
  get 'australia'       => 'countries#australia'
  get 'austria'         => 'countries#austria'
  get 'belgium'         => 'countries#belgium'
  get 'canada'          => 'countries#canada'
  get 'chile'           => 'countries#chile'
  get 'czech_republic'  => 'countries#czech_republic'
  get 'denmark'         => 'countries#denmark'
  get 'france'          => 'countries#france'
  get 'germany'         => 'countries#germany'
  get 'hungary'         => 'countries#hungary'
  get 'ireland'         => 'countries#ireland'
  get 'israel'          => 'countries#israel'
  get 'italy'           => 'countries#italy'
  get 'japan'           => 'countries#japan'
  get 'mexico'          => 'countries#mexico'
  get 'the_netherlands' => 'countries#the_netherlands'
  get 'new_zealand'     => 'countries#new_zealand'
  get 'poland'          => 'countries#poland'
  get 'portugal'        => 'countries#portugal'
  get 'romania'         => 'countries#romania'
  get 'sweden'          => 'countries#sweden'
  get 'taiwan'          => 'countries#taiwan'
  get 'united_kingdom'  => 'countries#united_kingdom'
  get 'usa'             => 'countries#usa'
end
